"""Generate exact integer reference vectors; no DUT outputs are used.

The FFT/IFFT equations follow 05_software/src/fft_transform.c, with Python
unbounded intermediates, arithmetic shifts, and division toward zero.
Run this script after changing the cases; generated constants live in the TB
so Vivado needs no extra source files or runtime data paths.
"""
import math
import random
from pathlib import Path

N = 512


def delta(k):
    angle = math.pi * int(f'{k:010b}'[::-1], 2) / 1024
    def rounded(x):
        return math.floor(x + .5) if x >= 0 else math.ceil(x - .5)
    return rounded(math.cos(angle) * 2**31), rounded(math.sin(angle) * 2**31)


def transform(values, inverse=False):
    f = list(values)
    m, t = (N // 2, 2) if inverse else (2, N // 2)
    while m > 1 if inverse else m < N:
        for u in range(m // 2):
            er, ei = delta(m + u)
            if inverse:
                ei = -ei
            for v in range(u * t, u * t + t // 2):
                j = v + t // 2
                ar, ai, br, bi = f[v], f[v + N//2], f[j], f[j + N//2]
                if inverse:
                    cr, ci = ar - br, ai - bi
                    out = ((ar + br) >> 1, (ai + bi) >> 1,
                           (cr * er - ci * ei) >> 32, (cr * ei + ci * er) >> 32)
                else:
                    cr, ci = br * er - bi * ei, br * ei + bi * er
                    out = (((ar << 31) + cr) >> 32, ((ai << 31) + ci) >> 32,
                           ((ar << 31) - cr) >> 32, ((ai << 31) - ci) >> 32)
                for index, value in zip((v, v+N//2, j, j+N//2), out):
                    assert -(2**31) <= value < 2**31, 'reference overflow'
                    f[index] = value
        m, t = (m // 2, t * 2) if inverse else (m * 2, t // 2)
    return f


def rebuild(q00, q01, w1, h0):
    a = transform([0] + [x << 20 for x in q00[1:]])
    b = transform([x << 17 for x in q01])
    c = transform([x << 19 for x in w1])
    quotient = [0] * N
    for i in range(N//2):
        v = (q00[0] << 12) + a[i]
        assert 0 < v < 2**30
        for index, x in ((i, b[i]*c[i] - b[i+N//2]*c[i+N//2]),
                         (i+N//2, b[i]*c[i+N//2] + b[i+N//2]*c[i])):
            assert abs(x) < v * 2**32
            quotient[index] = (abs(x)//v) * (-1 if x < 0 else 1)
            assert -(2**31) <= quotient[index] < 2**31
    t = transform(quotient, inverse=True)
    z = [(h * 256 + x) // 2**21 for h, x in zip(h0, t)]
    assert all(-8192 <= x < 8192 for x in z)
    return [h - 2*x for h, x in zip(h0, z)]


def main():
    # Analytic impulse anchors check normalization and both signs of floor.
    for sign, expected in ((1, -2), (-1, 4)):
        q = [1] + [0]*511
        p = [sign*24] + [0]*511
        w = [512] + [0]*511
        assert rebuild(q, p, w, [0]*N) == [expected] + [0]*511
    cases = []
    for case in range(3):
        q00 = [64] + [0]*511
        if case:
            q00[1], q00[511] = 3, -3
            q00[7], q00[505] = -2, 2
        rng = random.Random(20261002)
        q01 = [rng.randint(-1000, 1000) for i in range(N)]
        w1 = [rng.randint(-250, 250) for i in range(N)]
        if case == 2:
            q01 = [-x for x in q01]
        h0 = [(i*7 + i//3) % 2 for i in range(N)]
        expected = rebuild(q00, q01, w1, h0)
        assert any(x < 0 for x in expected) and any(x > 1 for x in expected)
        cases.append((q00, q01, w1, h0, expected))
        print(f'Case {case+4}: range {min(expected)}..{max(expected)}, '
              f'{sum(a != b for a,b in zip(expected,h0))} outputs differ from h0')
    lines = ['    -- BEGIN GENERATED REBUILD VECTORS',
             '    -- Generated by generate_vectors.py; integer fixed-point oracle.',
             '    type vector_t is array (0 to C_NUM_SAMPLES-1) of integer;',
             '    type case_vectors_t is array (0 to 2) of vector_t;']
    for col, name in enumerate(('Q00', 'Q01', 'W1', 'H0', 'EXPECTED')):
        lines.append(f'    constant C_{name} : case_vectors_t := (')
        for c, vectors in enumerate(cases):
            lines.append(f'        {c} => (')
            for start in range(0, N, 16):
                lines.append('            ' + ', '.join(map(str, vectors[col][start:start+16]))
                             + (',' if start+16 < N else ''))
            lines.append('        )' + (',' if c < 2 else ''))
        lines.append('    );')
    lines.append('    -- END GENERATED REBUILD VECTORS')
    tb = Path(__file__).with_name('rebuild_s0_tb.vhd')
    source = tb.read_text()
    begin, end = '    -- BEGIN GENERATED REBUILD VECTORS', '    -- END GENERATED REBUILD VECTORS'
    if begin in source:
        left, rest = source.split(begin, 1)
        _, right = rest.split(end, 1)
        source = left + '\n'.join(lines) + right
    else:
        source = source.replace('    signal clk ', '\n'.join(lines) + '\n\n    signal clk ', 1)
    tb.write_text(source)


if __name__ == '__main__':
    main()



